version: "3"
services:
  redis:
    image: redis:alpine
    container_name: "curso-redis"
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
 